export const REQUEST_FETCH_STYLE = 'REQUEST_FETCH_STYLE';
export const RECEIVE_FETCH_STYLE = 'RECEIVE_FETCH_STYLE';
export const ERROR_FETCH_STYLE = 'ERROR_FETCH_STYLE';
export const SELECT_CURRENT_STYLE = 'SELECT_CURRENT_STYLE';
export const CONFIRM_CURRENT_STYLE = 'CONFIRM_CURRENT_STYLE';
